### ISSUE TITLE
Feature request: custom keyboard support?

### ISSUE THREAD

**Issue by Jamesits** [jh0ker/mau_mau_bot#5]

**Comment by jh0ker** [comment]
Could you give a bit more information on this? 
To show cards, the inline API has been specifically chosen, since it provides the best user-interface (in my opinion). Also, it's an easy way to make sure you are not accidentally showing your cards to the rest of the group. 

Another thing: Pushing a custom keyboard to a single user in a group requires replying to a message of that user, which means:
- additional logic to find a users last message OR additional messages to reply to
- if the message limit for a group is hit (max. 30 msg per minute) the user can't play a card, because the bot can't send a message with the keyboard. Limits for inline queries are much less strict.

Other interface parts might be improved by using keyboards, do you have anything specific in mind for that?

**Comment by Jamesits** [comment]
I hope there is a button for displaying game status because it's not clear how to toggle it. Since custom keyboard cannot input text (but sends them directly) they are not as useful as I thought.
